Traceback (most recent call last):
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/tiepvu/w/tabml_book/tabml_book_env/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import tabml.datasets
import tabml
df_dict = tabml.datasets.download_movielen_1m()
df_dict.keys()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-1-42ad11713e2d>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# import tabml.datasets[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mtabml[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mdf_dict[0m [0;34m=[0m [0mtabml[0m[0;34m.[0m[0mdatasets[0m[0;34m.[0m[0mdownload_movielen_1m[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mdf_dict[0m[0;34m.[0m[0mkeys[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'tabml' has no attribute 'datasets'
AttributeError: module 'tabml' has no attribute 'datasets'

